// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzDlld2spK5Ubd0rp6K67TjyDkWKBZAaA',
    appId: '1:243895426560:web:368b0e5550888fb490c2e5',
    messagingSenderId: '243895426560',
    projectId: 'wholesight-1e971',
    authDomain: 'wholesight-1e971.firebaseapp.com',
    storageBucket: 'wholesight-1e971.firebasestorage.app',
    measurementId: 'G-YVR7XKN2ZK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAA2g1BS4NqKFhYiPtn_izJ-ugzpUPfmLA',
    appId: '1:243895426560:android:0e6035b4afdbc83290c2e5',
    messagingSenderId: '243895426560',
    projectId: 'wholesight-1e971',
    storageBucket: 'wholesight-1e971.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSwUHXFkMqOwnLlmDQKBOyIrp2ZxDZzys',
    appId: '1:243895426560:ios:6c9ee5d682b47df490c2e5',
    messagingSenderId: '243895426560',
    projectId: 'wholesight-1e971',
    storageBucket: 'wholesight-1e971.firebasestorage.app',
    iosBundleId: 'com.example.wholesight',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSwUHXFkMqOwnLlmDQKBOyIrp2ZxDZzys',
    appId: '1:243895426560:ios:6c9ee5d682b47df490c2e5',
    messagingSenderId: '243895426560',
    projectId: 'wholesight-1e971',
    storageBucket: 'wholesight-1e971.firebasestorage.app',
    iosBundleId: 'com.example.wholesight',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzDlld2spK5Ubd0rp6K67TjyDkWKBZAaA',
    appId: '1:243895426560:web:7e5f9973630082cd90c2e5',
    messagingSenderId: '243895426560',
    projectId: 'wholesight-1e971',
    authDomain: 'wholesight-1e971.firebaseapp.com',
    storageBucket: 'wholesight-1e971.firebasestorage.app',
    measurementId: 'G-7QD5KV173G',
  );
}
